### ISSUE TITLE
Advice regarding block formatting.

### ISSUE THREAD

**Issue by rarygit** [Awapic/IC#2]
Thanks for the plugin, it is very interesting to use, along with reading your book.

I do not have an Issue per se. As you do not have a Discussion section, I can only post here.

The advice you gave to use the simplify tool (Issue #1) was very helpful in terms of speed and in finishing the IC computation.

After some time (errors) and step-wise using distance increments, I was able to successfully complete an IC run for a walking distance of 400 m.

However I have only a vague grasp of whether I have a properly formatted the "blocks" upon which to operate the IC tool.
Like Issue 1, the blocks are not regular grids and were derived from a land use file, "dissolved" using AwaP, then simplified.
There are some large white spaces of public areas (e.g. parks, plaza etc).

Would you be able to comment on the attached files as to whether I have missed something or improve?
Attached is the original land use, the simplified blocks, the starting point and the result (400 m)   

Thanks for any suggestions, or confirmation that all is OK.

[Landuse.zip](https://github.com/Awapic/IC/files/6325831/Landuse.zip)
[Awap1394_simplified.zip](https://github.com/Awapic/IC/files/6325856/Awap1394_simplified.zip)
[IC_starting_point.zip](https://github.com/Awapic/IC/files/6325846/IC_starting_point.zip)
[IC_10729_400m.zip](https://github.com/Awapic/IC/files/6325841/IC_10729_400m.zip)

**Comment by imajic-unimelb** [comment]
Hi @rarygit , thank you for your comment and we are very glad that you find the plugin useful.

I looked at your blocks and they seem fine to me for the most part. There are quite a few parcels that are marked as land use = Garten, but I have looked at the Google street view in the area and these gardens are fenced off and not traversible by pedestrians so it is correct that they are included in blocks.
There is a long parcel in the north part of your catchment that is marked as land use = fließendes Gewässer (Wasserlauf), and this one did look odd as it is crossing the Muhlenring road and Motorikpark Hollabrunn (please see the Figure below). If this land use code is not actually preventing pedestrians from walking there, maybe you could filter it out.
![image](https://user-images.githubusercontent.com/32471563/115148687-0db55380-a0a4-11eb-96b3-f047e48a436d.png)
You might also consider running the AwaP plugin with the Dead-end removal option turned off. At the moment, AwaP is filling out some "tight" areas around your land use parcels which removes open space that should be available for walking around your blocks (please see the Figure below).
![image](https://user-images.githubusercontent.com/32471563/115148908-ead76f00-a0a4-11eb-80e7-63f0e14a41c5.png)

Hope this helps and please let us know if you have any more questions or ideas to share.

**Comment by rarygit** [comment]
Many thanks Ivan for taking the time to look through the data and comment!

It has answered my question very well.

As I am using AwaP to preprocess the blocks, I can see the need to make sure that the Dead-end removal is activated.

Regarding the Göllersbach (Wasserlauf, running water): if a road crosses a stream, or the riparian edge is public, should the water body be considered accessible, & therefore should be excluded from the "private area" blocks? 
In a general sense, I am thinking of urban water channels that are public space, but topographically inaccessible (e.g. steep slopes).

I will have more questions as I work through the material.

The particular issue I am addressing with AWAP & IC is examining the impact of housing::population intensification and its impact on climate and extreme weather event resilience. In the area of interest, intensification or densification seems to be occurring at the expense of walkability in favour of vehicle transport. For example, the latter exacerbates the anthropogenic heat factor and its contribution to the frequency and magnitude of summer heat waves. Walkability is an important concept for urban resilience. What is important is making it fit, with clarity, into a resilience assessment. 

The addition of a Discussion page would be helpful to discuss the application of AwaP and IC to actual urban issues.
